### ISSUE TITLE
Time problem -

### ISSUE THREAD

**Issue by nggolu** [Shipragupta14/Countdown-begins#1]
when user change the time while opening the one of the tab then time in the extension changes from for that particular website as you can see at the https://www.hackerearth.com in the image below. That will lead to wrong information.

![screenshot from 2017-06-15 15 37 14](https://user-images.githubusercontent.com/13465264/27178564-5670f192-51e8-11e7-9427-17f472cd5877.png)

**Comment by Shipragupta14** [comment]
Here the problem was that the hackerearth tab was already loaded before the extension gets enabled due to which the extension was not been able to detect its time duration. So, the solution is either reload the tab which is already loaded or open it again in the new tab by closing the earlier one after the extension gets enabled on the extension page in chrome.
